services:
  - type: web
    name: zijia-2d-survival
    env: node
    plan: free
    buildCommand: ""
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
